server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:file:./data/db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

camunda:
  bpm:
    database:
      schema-update: true
      # if you want to use H2 for Camunda, set this to "true"
    webapp:
      context-path: /camunda
    job-execution:
      enabled: true
    history-level: full

  # Optional: enable Camunda specific REST API configuration
  rest:
    enabled: true
    context-path: /camunda/engine

# Logging Configuration
logging:
  level:
    org.camunda.bpm: DEBUG

